name: BungeeSystem
version: 1.0
main: me.MrCodex.BungeeSystem.Main
author: Techevax
commands:
  ban:
  unban:
  tempban:
  check:
  banlist:
  mute:
  unmute:
  tempmute:
  mutelist:
  party:
  p:
  youtuber:
  rechte:
  restart:
  wartungen:
  tc:
  motd:
  setmax:
  warn:
  warns:
  werbung:
  ping:
  report:
  reports:
  list:
  cc:
  globalmute:
  me:
  bc:
  addpremium:
  joinme:
  xyserverxyx:
  adminsupport:
  support: